import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Image } from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, ExternalLink, User, Sparkles, Clock } from 'lucide-react-native';
import { WebView } from 'react-native-webview';

export default function ArticleScreen() {
  const router = useRouter();
  const params = useLocalSearchParams();

  const {
    title,
    originalTitle,
    summary,
    originalSummary,
    imageUrl,
    originalUrl,
    person,
    source,
    publishedAt,
  } = params;

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
          <ArrowLeft color="#fff" size={24} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Article Comparison</Text>
      </View>

      <ScrollView style={styles.content}>
        {/* AI Generated Section */}
        <View style={styles.section}>
          <View style={styles.aiLabelContainer}>
            <Sparkles color="#fff" size={18} />
            <Text style={styles.aiSectionLabel}>AI Generated by {person}</Text>
          </View>
          <View style={styles.articleCard}>
            <Image source={{ uri: Array.isArray(imageUrl) ? imageUrl[0] : imageUrl as string }} style={styles.articleImage} />
            <View style={styles.articleContent}>
              <Text style={styles.articleTitle}>{title}</Text>
              <View style={styles.articleMeta}>
                <View style={styles.metaItem}>
                  <User size={16} color="#666" />
                  <Text style={styles.metaText}>{person}</Text>
                </View>
                <View style={styles.metaItem}>
                  <Clock size={16} color="#666" />
                  <Text style={styles.metaText}>{publishedAt}</Text>
                </View>
              </View>
              <Text style={styles.articleSummary}>{summary}</Text>
            </View>
          </View>
          <View style={styles.fullArticleContainer}>
            <Text style={styles.fullArticleTitle}>Full AI Article</Text>
            <Text style={styles.fullArticleContent}>
              {generateFullAIArticle(person as string, title as string, summary as string)}
            </Text>
          </View>
        </View>

        {/* Divider */}
        <View style={styles.divider}>
          <Text style={styles.dividerText}>Original Article Below</Text>
        </View>

        {/* Original Article Section */}
        <View style={styles.section}>
          <View style={styles.originalLabelContainer}>
            <ExternalLink color="#fff" size={18} />
            <Text style={styles.originalSectionLabel}>Original Source: {source}</Text>
          </View>
          <View style={styles.articleCard}>
            <Image source={{ uri: Array.isArray(imageUrl) ? imageUrl[0] : imageUrl as string }} style={styles.articleImage} />
            <View style={styles.articleContent}>
              <Text style={styles.articleTitle}>{originalTitle}</Text>
              <View style={styles.articleMeta}>
                <View style={styles.metaItem}>
                  <User size={16} color="#666" />
                  <Text style={styles.metaText}>{source}</Text>
                </View>
                <View style={styles.metaItem}>
                  <Clock size={16} color="#666" />
                  <Text style={styles.metaText}>{publishedAt}</Text>
                </View>
              </View>
              <Text style={styles.articleSummary}>{originalSummary}</Text>
            </View>
          </View>
          <TouchableOpacity
            style={styles.readOriginalButton}
            onPress={() => {
              if (originalUrl) {
                router.push({ pathname: '/article', params: { url: originalUrl } });
              }
            }}
          >
            <ExternalLink color="#fff" size={18} />
            <Text style={styles.readOriginalButtonText}>Read Full Original Article</Text>
          </TouchableOpacity>
        </View>

        {/* WebView Placeholder for Original Article */}
        {originalUrl && (
          <View style={styles.webViewContainer}>
            <Text style={styles.webViewTitle}>Original Article Preview</Text>
            <View style={styles.webViewPlaceholder}>
              <Text style={styles.webViewPlaceholderText}>
                In a production app, this would show the original article in a WebView
              </Text>
              <Text style={styles.webViewUrl}>{originalUrl}</Text>
            </View>
          </View>
        )}
      </ScrollView>
    </View>
  );
}

// Template generator as in old UI
function generateFullAIArticle(person: string, title: string, summary: string): string {
  const articleTemplates: Record<string, string> = {
    'Albert Einstein': `
As I contemplate the intricate dance of particles and waves that governs our universe, I find myself drawn to examine this phenomenon through the lens of fundamental physics. The interconnectedness of all things becomes apparent when we observe how ${summary}

From my perspective, the elegant simplicity underlying complex systems reveals itself in this situation. Just as E=mc² demonstrates the profound relationship between mass and energy, so too does this development illuminate the deeper connections between human endeavor and natural law.

The curiosity that drives scientific inquiry compels us to ask not merely "what" but "why" and "how." In examining these events, we must remember that the universe operates according to principles that transcend our immediate understanding, yet reward patient observation and thoughtful analysis.

I am reminded of my belief that "imagination is more important than knowledge." While we must ground ourselves in facts and evidence, we must also dare to envision possibilities that extend beyond our current comprehension. This situation presents such an opportunity.

The responsibility of knowledge weighs heavily upon those who seek to understand the world's complexities. As we witness these developments unfold, we must remember that our role is not merely to observe, but to contribute to the greater understanding of humanity's place in the cosmos.
`,
    'Oprah Winfrey': `
What moves me most deeply about this story is the human element at its core. Behind every headline, every statistic, every development, there are real people with real dreams, real struggles, and real triumphs. ${summary}

I've learned through my years of connecting with people from all walks of life that our stories are what bind us together. This situation reminds me of the countless conversations I've had where someone's vulnerability led to breakthrough, where their courage inspired others to find their own strength.

The power of authenticity shines through in moments like these. When we strip away the noise and the speculation, we're left with fundamental human truths about resilience, hope, and the capacity for growth. I see in this development an opportunity for all of us to reflect on what truly matters.

What I know for sure is that every challenge presents an opportunity for transformation. The individuals affected by these circumstances have within them the power to not just survive, but to thrive. Their stories will inspire others, creating ripples of positive change that extend far beyond what we can imagine.

As we witness these events unfold, I encourage each of us to approach them with empathy, understanding, and a willingness to learn. The greatest gift we can give one another is our presence, our attention, and our belief in the possibility of better days ahead.

This is what I see when I look at this situation: not just facts and figures, but the beautiful, complex, ever-evolving story of human experience. And that story, my friends, is one worth celebrating.
`,
    'Elon Musk': `
Looking at this situation from first principles, we need to break down the problem to its fundamental components. ${summary} This represents both a challenge and an opportunity to innovate our way to a better solution.

The question I always ask is: what would it take to make this 10 times better? Incremental improvements aren't enough when we're dealing with challenges of this magnitude. We need to think exponentially, not linearly.

From an engineering perspective, every problem is solvable with the right combination of talent, resources, and determination. The key is to identify the biggest bottlenecks and attack them with relentless focus. We can't afford to optimize for the wrong variables.

What excites me about this development is the potential for technological solutions that could fundamentally change how we approach similar challenges in the future. Whether we're talking about sustainable energy, space exploration, or artificial intelligence, the principles remain the same: identify the physics constraints, gather the best team possible, and iterate rapidly.... The timeline for meaningful change is always faster than people think, but slower than we'd like. That's why we need to maintain urgency while also being realistic about the complexity of the problems we're trying to solve.

We're living in the most exciting time in human history. The tools we have access to today - from advanced manufacturing to artificial intelligence to global communication networks - give us unprecedented ability to solve problems that previous generations could only dream of addressing.

The future is going to be wild, and developments like this are just the beginning of what's possible when human ingenuity meets cutting-edge technology.
`,
    'Default': `
This development represents a significant moment in our ongoing dialogue about the challenges and opportunities facing our world today. ${summary}

As we examine the various facets of this story, it becomes clear that we are witnessing a convergence of factors that will likely influence how we approach similar situations in the future. The complexity of modern issues requires us to consider multiple perspectives and potential outcomes.

The human element in this story cannot be overlooked. Behind every policy decision, every technological advancement, and every social movement are individuals whose lives are directly affected by these changes. Their experiences provide valuable insights into the real-world implications of these developments.

From a broader perspective, this situation highlights the interconnected nature of our global society. Actions and decisions in one area often have far-reaching consequences that extend well beyond their immediate context. Understanding these connections is crucial for anyone seeking to make informed decisions about the future.

The path forward requires careful consideration of both immediate needs and long-term implications. While it's tempting to focus solely on short-term solutions, sustainable progress often requires us to take a more comprehensive view of the challenges we face.

As we continue to monitor these developments, it's important to maintain both optimism about our collective ability to address complex challenges and realism about the work that lies ahead. The solutions we develop today will shape the world we leave for future generations.
`
  };
  return articleTemplates[person as keyof typeof articleTemplates] || articleTemplates.Default;
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  header: { backgroundColor: '#BB1919', paddingTop: 60, paddingBottom: 16, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center' },
  backButton: { marginRight: 16 },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: '#fff' },
  content: { flex: 1 },
  section: { padding: 16 },
  sectionHeader: { marginBottom: 16 },
  aiLabelContainer: { backgroundColor: '#4CAF50', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start' },
  aiSectionLabel: { color: '#fff', fontSize: 14, fontWeight: '600', marginLeft: 8 },
  originalLabelContainer: { backgroundColor: '#1E3A8A', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start' },
  originalSectionLabel: { color: '#fff', fontSize: 14, fontWeight: '600', marginLeft: 8 },
  articleCard: { backgroundColor: '#fff', borderRadius: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 4, overflow: 'hidden' },
  articleImage: { width: '100%', height: 200, backgroundColor: '#f0f0f0' },
  articleContent: { padding: 20 },
  articleTitle: { fontSize: 20, fontWeight: 'bold', color: '#1a1a1a', marginBottom: 12, lineHeight: 28 },
  articleMeta: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  metaItem: { flexDirection: 'row', alignItems: 'center' },
  metaText: { fontSize: 14, color: '#666', marginLeft: 4 },
  articleSummary: { fontSize: 16, color: '#666', lineHeight: 24, marginBottom: 20 },
  fullArticleContainer: { borderTopWidth: 1, borderTopColor: '#e9ecef', paddingTop: 20 },
  fullArticleTitle: { fontSize: 18, fontWeight: 'bold', color: '#1a1a1a', marginBottom: 12 },
  fullArticleContent: { fontSize: 16, color: '#333', lineHeight: 26 },
  divider: { paddingVertical: 20, alignItems: 'center' },
  dividerText: { fontSize: 16, fontWeight: '600', color: '#666', backgroundColor: '#f8f9fa', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, borderWidth: 2, borderColor: '#e9ecef' },
  readOriginalButton: { backgroundColor: '#1E3A8A', paddingHorizontal: 16, paddingVertical: 12, borderRadius: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 16 },
  readOriginalButtonText: { color: '#fff', fontSize: 16, fontWeight: '600', marginLeft: 8 },
  webViewContainer: { margin: 16, backgroundColor: '#fff', borderRadius: 12, padding: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 4 },
  webViewTitle: { fontSize: 18, fontWeight: 'bold', color: '#1a1a1a', marginBottom: 16, textAlign: 'center' },
  webViewPlaceholder: { alignItems: 'center', padding: 40, backgroundColor: '#f8f9fa', borderRadius: 8, borderWidth: 2, borderColor: '#e9ecef', borderStyle: 'dashed' },
  webViewPlaceholderText: { fontSize: 16, color: '#666', textAlign: 'center', marginVertical: 16, lineHeight: 22 },
  webViewUrl: { fontSize: 12, color: '#999', textAlign: 'center' },
});

